default_language_version:
    python: python3
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: flake8
        language: python
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
