version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  rabbit_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./stock_service/Dockerfile
    image: s_local_django
    depends_on:
      - postgres
    volumes:
      - .:/service
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432

    ports:
      - "8000:8000"

  postgres:
    image: postgres:12.3
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
