# Generated by Django 3.1.7 on 2022-12-28 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('COM', 'Success'), ('ERR', 'Error')], max_length=3, null=True)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
        migrations.DeleteModel(
            name='UserRequestHistory',
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['symbol'], name='api_request_symbol_d67b16_idx'),
        ),
    ]
