# Generated by Django 3.1.7 on 2022-12-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221228_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
